### ISSUE TITLE
Error in predict function

### ISSUE THREAD

**Issue by minsu1794** [gpp-rnd/rs3#10]
Hello I have installed as instructed and I am trying to run your predict function based on the example file you have "sgrna-designs_BCL2L1_MCL1_EEF2.txt". And I am encountering error regarding to imputer:

/home/mcho43/anaconda3/envs/scWork/lib/python3.8/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator SimpleImputer from version 1.0.dev0 when using version 1.3.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/mcho43/anaconda3/envs/scWork/lib/python3.8/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator Pipeline from version 1.0.dev0 when using version 1.3.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mcho43/anaconda3/envs/scWork/lib/python3.8/site-packages/rs3/predict.py", line 118, in predict
    out_df[target_score_col] = predict_target(design_df=out_df, aa_subseq_df=aa_subseq_df,
  File "/home/mcho43/anaconda3/envs/scWork/lib/python3.8/site-packages/rs3/predicttarg.py", line 47, in predict_target
    predictions = model.predict(X_target)
  File "/home/mcho43/anaconda3/envs/scWork/lib/python3.8/site-packages/sklearn/pipeline.py", line 514, in predict
    Xt = transform.transform(Xt)
  File "/home/mcho43/anaconda3/envs/scWork/lib/python3.8/site-packages/sklearn/utils/_set_output.py", line 157, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/mcho43/anaconda3/envs/scWork/lib/python3.8/site-packages/sklearn/impute/_base.py", line 530, in transform
    X = self._validate_input(X, in_fit=False)
  File "/home/mcho43/anaconda3/envs/scWork/lib/python3.8/site-packages/sklearn/impute/_base.py", line 305, in _validate_input
    if not in_fit and self._fit_dtype.kind == "O":
AttributeError: 'SimpleImputer' object has no attribute '_fit_dtyp

I believe is version conflict and my scikit-learn version is 1.3.2.

**Comment by PeterDeWeirdt** [comment]
I've updated the package so sklearn v 0.24.2 will be installed. Hopefully this will fix this issue
